import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import LoadingSpinner from '../components/LoadingSpinner';
import Pricing from '../components/pricing/Pricing';
import PricingHeadline from '../components/pricing/PricingHeadline';
import PatternCircles from '../components/svg/PatternCircles';

const Home: NextPage = () => {
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Prototype loading state
    setTimeout(() => {
      setLoading(false);
    }, 1600);
  });

  return (
    <div>
      <Head>
        <title>Interactive pricing component | frontendmentor.io</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon-32x32.png" type="image/png" />
      </Head>

      <main className="min-h-screen">
        <div className="absolute top-0 w-full h-[50vh] bg-bg-pattern bg-no-repeat bg-cover bg-left"></div>

        {loading && (
          <div className="fixed inset-0 flex items-center justify-center">
            <LoadingSpinner />
          </div>
        )}

        {!loading && <PricingHeadline />}

        {!loading && <Pricing />}
      </main>
    </div>
  );
};

export default Home;
