import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Interactive pricing component | frontendmentor.io</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/favicon-32x32.png" type="image/png" />
      </Head>

      <main>
        <h1 className="text-9xl">Hello, world</h1>
      </main>
    </div>
  );
};

export default Home;
